import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { RiMovie2Line } from "react-icons/ri";


const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ITIMOV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.variable} antialiased`}>
      <div className="flex items-center px-10 py-5 border-b-1 border-gray-200 justify-between p-4 font-bold text-lg text-white">
        <div className="flex gap-3">
          <RiMovie2Line size={28} />
          <h3>IT-IMOV</h3>
        </div>
      </div>
        {children}
      </body>
    </html>
  );
}